# Sandbox config example

# global parameters
project_name: 'stack-v2-sandbox'
experiment_name: 'stack-v2-sandbox-run0'              # for wandb tracer name
work_dir: './outputs/stack-v2-sandbox'                # the default output dir for meta logging
hpo_config: null                                  # path to a configuration file when using auto-HPO tool.

# configs for each job, the jobs will be executed according to the order in the list
probe_job_configs:
  - hook: 'ProbeViaAnalyzerHook'
    meta_name: 'analysis_ori_data'
    dj_configs: 'configs/predict/stack-v2-python-refine.yaml'
    extra_configs:

refine_recipe_job_configs:
  - hook: 'RefineRecipeViaKSigmaHook'
    meta_name: 'analysis_ori_data'
    dj_configs: 'configs/predict/stack-v2-python-refine.yaml'
    extra_configs:
      path_k_sigma_recipe: './outputs/stack-v2-sandbox/k_sigma_new_recipe.yaml'