# Process config example for dataset

# global parameters
project_name: 'analyzer-python-syntax-error'
dataset_path: '/mnt/tmp/apps/cmss-yangjiandong/data-juicer/configs/demo/python_syntax_error/python-code-test.jsonl'  # path to your dataset directory or file
np: 1  # number of subprocess to process your dataset

export_path: './outputs/analyzer-python-syntax-error/analyzer-syntax-result.jsonl'
text_keys: 'text'
# process schedule
# a list of several process operators with their arguments
process:
  - code_syntax_error_filter:  