# global parameters
project_name: 'the-stack-v2-full-C++'
dataset_path: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-c++'  # path to your dataset directory or file
export_path: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-c++-pipleline/the-stack-v2-full-c++-filter.parquet'
text_keys: 'text'
use_cache: true
ds_cache_dir: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-c++-pipleline/cache'
np: 20  # number of subprocess to process your dataset
open_tracer: false

# process schedule
# a list of several process operators with their arguments
process:
#   - code_muti_language_syntax_filter:
#       language: 'cpp'
  - alphanumeric_filter:
      tokenization: False
      min_ratio: 0.289
      max_ratio: 0.905
  - alphanumeric_filter:
      tokenization: True
      min_ratio: 0.269
      max_ratio: 3
  - average_line_length_filter:
      min_len: 10
      max_len: 60
  - character_repetition_filter:
      rep_len: 10
      min_ratio: 0.05
      max_ratio: 0.44
  - maximum_line_length_filter:
      min_len: 20
      max_len: 500
  - text_length_filter:
      min_len: 58
  - words_num_filter:
      lang: en
      tokenization: False
      min_num: 5
      max_num: 3200
  - word_repetition_filter:
      lang: en
      tokenization: False
      rep_len: 10
      max_ratio: 0.28
#   - document_simhash_deduplicator:
#       tokenization: space
#       window_size: 6
#       lowercase: true
#       ignore_pattern: '\p{P}'
#       num_blocks: 6
#       hamming_distance: 4
  - clean_email_mapper:
  - clean_links_mapper:
  - fix_unicode_mapper:
  - punctuation_normalization_mapper:
  - whitespace_normalization_mapper:
  - clean_copyright_mapper:
