# global parameters
project_name: 'starcoderdata'
dataset_path: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-java/score/part8/the-stack-v2-java-score8.parquet'  # path to your dataset directory or file
export_path: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-java/score/part8/the-stack-v2-java-filterscore8.parquet'
text_keys: 'text'
suffixes: ['.parquet']
np: 10  # number of subprocess to process your dataset
open_tracer: true
trace_num: 10
ds_cache_dir: '/mnt/tmp/apps/cmss-yangjiandong/data/the-stack-v2-full-java/score/cache'

# process schedule
# a list of several process operators with their arguments
process:
  - score_filter:
      min_score: 0.25
